### ISSUE TITLE
TEST API 문의 드립니다.

### ISSUE THREAD

**Issue by cow6099** [plusfriend/auto_reply#248]
@또롱의IT사전

URL: **http://1.224.170.201:9000/keyboard**

Required*
**Initialize Api test : Fail 415 : wrong keyboard initialization**
Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200

API 테스트하면 위와 같은 에러 메세지가 출력 됩니다.
크롬 브라우저에서 http://1.224.170.201:9000/keyboard 하면 정상 동작 합니다.

Required 에서만 Fail이 발생 하는데 어떤 부분이 문제인지 궁금합니다.

### Console
```
_월 15, 2017 8:45:54 오후 org.apache.catalina.core.StandardWrapperValve invoke
심각: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Could not resolve view with name 'keyboard' in servlet with name 'dispatcher'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'keyboard' in servlet with name 'dispatcher'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1190)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:992)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:939)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)_
```

**Comment by plusfriendteam** [comment]
구현에 관련된 문제는 저희가 답변을 드리기 어렵네요.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 참고하세요.

**Comment by cow6099** [comment]
테스트 결과를 보면 Optional 항목은 문제 없이 OK 되는것을 볼 수 있는데
Required 만 Fail 뜨는 이유를 대략적으로도 알 수 없나요?
