### ISSUE TITLE
API 형 오류

### ISSUE THREAD

**Issue by cws11** [plusfriend/auto_reply#727]
API 타입의 서비스를 지금까지 사용하면서 문제가 없었습니다. 
몇일전부터 계속 아래와 같은 메세지를 수신받습니다. 

사용자 봇 서버에 에러가 감지되었습니다.
내용 : [잘못된 응답입니다. response is not OK(200) : 500 / Internal Server Error]

※ 이 메시지는 관리자에게만 발송되는 봇 모니터링 메시지입니다.

※ 모니터링 메시지 수신을 원치 않으시면플러스친구 관리자센터 > 스마트채팅 API형 >알림 받을 전화번호에서 전화번호를 삭제해주세요.

해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

관련하여 테스트 주소는 http://141.223.105.191:8002 입니다. 
test 버튼 클릭시 정상적으로 응답합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
실제 해당 주소의 /message API 를 요청하면 500 Internal Server Error 가 내려오고 있습니다.

$ curl -XPOST http://141.223.105.191:8002/message -H 'Content-Type:application/json; charset=utf-8' -d '{"type": "text", "content": "CompressorDischargePressure"}'  -i 
알려주신 주소로 위와 같이 요청했을 때, 아래와 같은 응답이 내려옵니다.

HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1180
Date: Thu, 08 Nov 2018 06:52:07 GMT
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: CompressorDischargePressure.toFixed is not a function<br> &nbsp; &nbsp;at /usr/local/bin/kakao/PLS-II-RF-CG.js:115:88<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/local/bin/kakao/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/usr/local/bin/kakao/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/usr/local/bin/kakao/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/local/bin/kakao/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /usr/local/bin/kakao/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/usr/local/bin/kakao/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/usr/local/bin/kakao/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at /usr/local/bin/kakao/node_modules/body-parser/lib/read.js:130:5<br> &nbsp; &nbsp;at invokeCallback (/usr/local/bin/kakao/node_modules/raw-body/index.js:224:16)</pre>
</body>
</html>

위의 에러 내용과 더불어 /keyboard API 도 Content-Type 이 text/html; charset=utf-8 으로 내려오고 있으니 application/json; charset=utf-8 로 수정해주시기 바랍니다.
감사합니다.
